pipeline:
  job_name: ingestion_job

destination:
  name: bq_gold
  type: bigquery
  project_id: african-tech-skills-c295
  dataset_id: 03_gold
  location: EU

sources:
  - name: gcs_raw
    type: gcs
    bucket_name: bkt-dp-tf-state
    tables:
      - name: new_customers_20_06
        object_name: demo.csv
        mode: append
        sep: ";"
        schema:
          - dddd: STRING
          - zzzz: STRING
          - aaaa: STRING
      - name: new_customers_20_06_v2
        object_name: demo.csv
        mode: append
        sep: ";"
        schema:
          - dddd: STRING
          - zzzz: STRING
          - aaaa: STRING

  - name: drive_reports
    type: google_drive
    tables:
      - name: monthly_report_2103
        file_id: "1PGuUkYTSjOSIjIv_qi3ga6lsH8Sz7bxn"
        mode: append
        sep: ";"
        schema:
          - dddd: STRING
          - zzzz: STRING
          - aaaa: STRING
